[alias]
boff = "build --no-default-features --features off-logs"
be = "build --no-default-features --features error-logs"
bw = "build --no-default-features --features warn-logs"
bd = "build --no-default-features --features debug-logs"
bt = "build --no-default-features --features trace-logs"

broff = "build --release --no-default-features --features off-logs"
bre = "build --release --no-default-features --features error-logs"
brw = "build --release --no-default-features --features warn-logs"
brd = "build --release --no-default-features --features debug-logs"
brt = "build --release --no-default-features --features trace-logs"