[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "polypus_python"
version = "0.0.1"
dependencies = [
    "requests",
    'importlib-metadata; python_version<"3.10"',
]

[tool.setuptools]
include-package-data = true
